name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.13.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn
    - run: npm test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        template: ' $CHANGES '
        categories: |
          [{
            "title": "New features",
            "labels": ["feature", "enhancement"]
          }, {
            "title": "Bug fixes and improvements",
            "labels": ["bug"]
          }]
